# -*- coding: utf-8 -*-
"""salary_regression_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18i3ISnTl4QvzChUBR2CO15Vsaxa5t-l8

## Import necessary libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import r2_score

"""## Load the dataset"""

data = pd.read_csv("w2_position_salaries.csv")
X = data[["Level"]].values # input feature
y = data["Salary"].values # target

"""## Simple Linear Regression"""

lin_reg = LinearRegression()
lin_reg.fit(X, y)
y_pred_lin = lin_reg.predict(X)
r2_lin = r2_score(y, y_pred_lin)
print("R² Score (Linear Regression):", r2_lin)

"""## Polynomial Regression (degree 2, 3, 4)"""

for degree in [2, 3, 4]:
  poly = PolynomialFeatures(degree=degree)
  X_poly = poly.fit_transform(X)

  poly_reg = LinearRegression()
  poly_reg.fit(X_poly, y)

  y_pred_poly = poly_reg.predict(X_poly)
  r2_poly = r2_score(y, y_pred_poly)

  print(f"R² Score (Polynomial Regression, degree {degree}):", r2_poly)

"""## Optional Visualization"""

plt.scatter(X, y, color="red", label="Actual Data")
plt.plot(X, y_pred_lin, color="blue", label="Linear Regression")

"""## Plot polynomial fits"""

colors = ["green", "orange", "purple"]
for i, degree in enumerate([2, 3, 4]):
  poly = PolynomialFeatures(degree=degree)
  X_poly = poly.fit_transform(X)
  poly_reg = LinearRegression()
  poly_reg.fit(X_poly, y)
  plt.plot(X, poly_reg.predict(X_poly), color=colors[i], label=f"Poly deg {degree}")

plt.xlabel("Level")
plt.ylabel("Salary")
plt.legend()
plt.show()